#!/usr/bin/env python3

import re
from random import choice

from plugin import BasicPlugin

class Plugin(BasicPlugin):
	"""Asl - Random Age/Sex/Location Generator"""

	def __init__(self, bot):
		self.bot = bot
		self.name = "asl"
		self.priority = 50
		self.load_priority = 10

		self.Genders = ['m'
			,'f'
			,'herm'
			,'trans'
			,'male'
			,'female'
			,'kangaroo'
			,'asexual'
			]

		self.Ages = list(range(5, 100))

		self.Locations = ['Alabama'
			,'Alaska'
			,'American Samoa'
			,'Arizona'
			,'Arkansas'
			,'California'
			,'Colorado'
			,'Connecticut'
			,'Delaware'
			,'District of Columbia'
			,'Florida'
			,'Georgia'
			,'Guam'
			,'Hawaii'
			,'Idaho'
			,'Illinois'
			,'Indiana'
			,'Iowa'
			,'Kansas'
			,'Kentucky'
			,'Louisiana'
			,'Maine'
			,'Maryland'
			,'Massachusetts'
			,'Michigan'
			,'Minnesota'
			,'Mississippi'
			,'Missouri'
			,'Montana'
			,'Nebraska'
			,'Nevada'
			,'New Hampshire'
			,'New Jersey'
			,'New Mexico'
			,'New York'
			,'North Carolina'
			,'North Dakota'
			,'Northern Marianas Islands'
			,'Ohio'
			,'Oklahoma'
			,'Oregon'
			,'Pennsylvania'
			,'Puerto Rico'
			,'Rhode Island'
			,'South Carolina'
			,'South Dakota'
			,'Tennessee'
			,'Texas'
			,'Utah'
			,'Vermont'
			,'Virginia'
			,'Virgin Islands'
			,'Washington'
			,'West Virginia'
			,'Wisconsin'
			,'Wyoming'
			,'Dover'
			,'Harrisburg'
			,'Trenton'
			,'Atlanta'
			,'Hartford'
			,'Boston'
			,'Annapolis'
			,'Columbia'
			,'Concord'
			,'Richmond'
			,'Albany'
			,'Raleigh'
			,'Providence'
			,'Montpelier'
			,'Frankfort'
			,'Nashville'
			,'Columbus'
			,'Baton Rouge'
			,'Indianapolis'
			,'Jackson'
			,'Springfield'
			,'Montgomery'
			,'Augusta'
			,'Jefferson City'
			,'Little Rock'
			,'Lansing'
			,'Tallahassee'
			,'Austin'
			,'Des Moines'
			,'Madison'
			,'Sacramento'
			,'St. Paul'
			,'Salem'
			,'Topeka'
			,'Charleston'
			,'Carson City'
			,'Lincoln'
			,'Denver'
			,'Bismarck'
			,'Pierre'
			,'Helena'
			,'Olympia'
			,'Boise'
			,'Cheyenne'
			,'Salt Lake City'
			,'Oklahoma City'
			,'Santa Fe'
			,'Phoenix'
			,'Juneau'
			,'Honolulu'
			,'Afghanistan'
			,'Albania'
			,'Algeria'
			,'Andorra'
			,'Angola'
			,'Antigua & Deps'
			,'Argentina'
			,'Armenia'
			,'Australia'
			,'Austria'
			,'Azerbaijan'
			,'Bahamas'
			,'Bahrain'
			,'Bangladesh'
			,'Barbados'
			,'Belarus'
			,'Belgium'
			,'Belize'
			,'Benin'
			,'Bhutan'
			,'Bolivia'
			,'Bosnia Herzegovina'
			,'Botswana'
			,'Brazil'
			,'Brunei'
			,'Bulgaria'
			,'Burkina'
			,'Burundi'
			,'Cambodia'
			,'Cameroon'
			,'Canada'
			,'Cape Verde'
			,'Central African Rep'
			,'Chad'
			,'Chile'
			,'China'
			,'Colombia'
			,'Comoros'
			,'Congo'
			,'Congo - Democratic Rep'
			,'Costa Rica'
			,'Croatia'
			,'Cuba'
			,'Cyprus'
			,'Czech Republic'
			,'Denmark'
			,'Djibouti'
			,'Dominica'
			,'Dominican Republic'
			,'East Timor'
			,'Ecuador'
			,'Egypt'
			,'El Salvador'
			,'Equatorial Guinea'
			,'Eritrea'
			,'Estonia'
			,'Ethiopia'
			,'Fiji'
			,'Finland'
			,'France'
			,'Gabon'
			,'Gambia'
			,'Georgia'
			,'Germany'
			,'Ghana'
			,'Greece'
			,'Grenada'
			,'Guatemala'
			,'Guinea'
			,'Guinea-Bissau'
			,'Guyana'
			,'Haiti'
			,'Honduras'
			,'Hungary'
			,'Iceland'
			,'India'
			,'Indonesia'
			,'Iran'
			,'Iraq'
			,'Ireland - Republic'
			,'Israel'
			,'Italy'
			,'Ivory Coast'
			,'Jamaica'
			,'Japan'
			,'Jordan'
			,'Kazakhstan'
			,'Kenya'
			,'Kiribati'
			,'Korea North'
			,'Korea South'
			,'Kosovo'
			,'Kuwait'
			,'Kyrgyzstan'
			,'Laos'
			,'Latvia'
			,'Lebanon'
			,'Lesotho'
			,'Liberia'
			,'Libya'
			,'Liechtenstein'
			,'Lithuania'
			,'Luxembourg'
			,'Macedonia'
			,'Madagascar'
			,'Malawi'
			,'Malaysia'
			,'Maldives'
			,'Mali'
			,'Malta'
			,'Marshall Islands'
			,'Mauritania'
			,'Mauritius'
			,'Mexico'
			,'Micronesia'
			,'Moldova'
			,'Monaco'
			,'Mongolia'
			,'Montenegro'
			,'Morocco'
			,'Mozambique'
			,'Myanmar / Burma'
			,'Namibia'
			,'Nauru'
			,'Nepal'
			,'Netherlands'
			,'New Zealand'
			,'Nicaragua'
			,'Niger'
			,'Nigeria'
			,'Norway'
			,'Oman'
			,'Pakistan'
			,'Palau'
			,'Panama'
			,'Papua New Guinea'
			,'Paraguay'
			,'Peru'
			,'Philippines'
			,'Poland'
			,'Portugal'
			,'Qatar'
			,'Romania'
			,'Russian Federation'
			,'Rwanda'
			,'St Kitts & Nevis'
			,'St Lucia'
			,'Saint Vincent & the Grenadines'
			,'Samoa'
			,'San Marino'
			,'Sao Tome & Principe'
			,'Saudi Arabia'
			,'Senegal'
			,'Serbia'
			,'Seychelles'
			,'Sierra Leone'
			,'Singapore'
			,'Slovakia'
			,'Slovenia'
			,'Solomon Islands'
			,'Somalia'
			,'South Africa'
			,'South Sudan'
			,'Spain'
			,'Sri Lanka'
			,'Sudan'
			,'Suriname'
			,'Swaziland'
			,'Sweden'
			,'Switzerland'
			,'Syria'
			,'Taiwan'
			,'Tajikistan'
			,'Tanzania'
			,'Thailand'
			,'Togo'
			,'Tonga'
			,'Trinidad & Tobago'
			,'Tunisia'
			,'Turkey'
			,'Turkmenistan'
			,'Tuvalu'
			,'Uganda'
			,'Ukraine'
			,'United Arab Emirates'
			,'United Kingdom'
			,'United States'
			,'Uruguay'
			,'Uzbekistan'
			,'Vanuatu'
			,'Vatican City'
			,'Venezuela'
			,'Vietnam'
			,'Yemen'
			,'Zambia'
			,'Zimbabwe'
		]


	def finish(self):
		pass

	def hook(self):
		self.bot.config.set_safe("plugins."+self.name, None, "Asl - Random Age/Sex/Location Generator")
		return True

	def call(self, message):
		if message.command == "PRIVMSG":
			if re.search("(?:\s+?|^)asl(?:\s+?|$)", " ".join(message.params[1:])):
				origin = message.params[0] if message.params[0] != self.bot.ircsock.getnick() else message.origin()[1:]
				self.bot.ircsock.say(origin, "{0}/{1}/{2}".format(choice(self.Ages), choice(self.Genders), choice(self.Locations)))




